### ISSUE TITLE
работа с ajax

### ISSUE THREAD

**Issue by timz** [loveorigami/yii2-magnific-popup#1]
Можно какой то пример работы с типом контента ajax?
я столкнулся с такой же проблемой что и здесь https://toster.ru/q/326042 ловлю редирект при сохранении модели вместо json ответа, не соображу что делаю не так.

**Comment by loveorigami** [comment]
Это просто обертка над popup. Если есть проблемы, значит проблемы именно в нем.
И для работы с ajax я его не использую.

Для этих целей у меня есть другой виджет - https://github.com/loveorigami/yii2-modal-ajax
который покрывает очень много разных случаев применения - просто контент, формы редактирования (добавления), crud в гриде и др...

**Comment by timz** [comment]
да. я его тоже попробовал. оно у вас конфликтует с https://www.malot.fr/bootstrap-datetimepicker/
при открытии календарика модальное окно уходит в перезагрузку.

**Comment by loveorigami** [comment]
Потому что это устаревший плагин еще и под 2 бутсрап. 
https://github.com/smalot/bootstrap-datetimepicker

У меня 3 datepicker-a, и все работают корректно
- от картика
- flatpickr https://github.com/loveorigami/yii2-flatpickr
- https://github.com/loveorigami/yii2-daterange-picker-ex

**Comment by timz** [comment]
с проблемой разобрался. form post и ajax post оказалось не одно и тоже)) глянул пикеры.
к сожалению они не подошли. катрик тянет за собой много всего, flatpickr - это не бутстрап. рендж пикер - специфичный). К слову работаю на 4 бустрапе, датапикер с которым работаю - работает на нем без глюков) Благодарю.
